if(WIN32)
    set(FUGUE_PLATFORM "Windows")
    add_compile_definitions(FUGUE_PLATFORM_WINDOWS=1)
elseif(APPLE)
    set(FUGUE_PLATFORM "macOS")
    add_compile_definitions(FUGUE_PLATFORM_MACOS=1)
elseif(UNIX)
    if(CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
        set(FUGUE_PLATFORM "FreeBSD")
        add_compile_definitions(FUGUE_PLATFORM_FREEBSD=1)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "OpenBSD")
        set(FUGUE_PLATFORM "OpenBSD")
        add_compile_definitions(FUGUE_PLATFORM_OPENBSD=1)
    elseif(ANDROID)
        set(FUGUE_PLATFORM "Termux")
        add_compile_definitions(FUGUE_PLATFORM_TERMUX=1)
    else()
        set(FUGUE_PLATFORM "Linux")
        add_compile_definitions(FUGUE_PLATFORM_LINUX=1)
    endif()
endif()
